1.2.1
fix problem with parsing multiple arguments

diff --git a/resync b/resync
--- a/resync
+++ b/resync
@@ -29,6 +29,8 @@ declare -r clear='\033[0m'
 # etc stuff
 declare sourceopts='yes'
 declare dopost='yes'
+declare dosync='yes'
+declare doremove='yes'
 
 fatal() {
   printf "\n${redbold}Fatal error: ${red}%s\n ${clear}" "$*"
@@ -43,34 +45,42 @@ Usage: $0 [options]
 -h    show this usage text
 -s    skip running repo sync
 -o    skip syncing rom source optimizations
+-c    skip deleting conflicting directories
 -d    skip resyncing deleted directories
 
-version: 1.2
+Running with -s will automatically toggle -d.
+
+version: 1.2.1
 EOF
 
 exit 0
 }
 
 args() {
-  while getopts ":sod" opts; do
+  while getopts ":sodc" opts; do
     case "${opts}" in
       "s")
-        # skip to post
-        printf "${bluebold}>> ${blue}Argument '-s' given, skipping sync\n${clear}"
-        post && exit 0
+        # do not sync
+        # printf "${bluebold}>> ${blue}Argument '-s' given, skipping sync\n${clear}"
+        declare dosync="no"
         ;;
     
       "o")
         # let the script know to not apply source optimizations
-        printf "${bluebold}>> ${blue}Argument '-o' given, skipping source optimization\n${clear}"
+        # printf "${bluebold}>> ${blue}Argument '-o' given, skipping source optimization\n${clear}"
 	declare sourceopts="no"
         ;;
 
       "d")
         # do not reclone deleted directories
-        printf "${bluebold}>> ${blue}Argument '-d' given, skipping post-sync\n${clear}"
+        # printf "${bluebold}>> ${blue}Argument '-d' given, skipping post-sync\n${clear}"
 	declare dopost="no"
         ;;
+
+      "c")
+	# do not remove deleted directories
+	declare doremove="no"
+	;;
 
       *)
         usage
@@ -83,16 +93,24 @@ args() {
 }
 
 firstrun() {
-  # let the output of 'repo sync' tell us what to delete
-  printf "${cyanbold}>> ${cyan}First run of 'repo sync' to determine directories that need to be recloned\n${clear}"
-  if repo sync -j"$(nproc --all)" --no-tags --no-clone-bundle --current-branch --force-sync &> "$DIRS" ; then
-    printf "${magenta}The first run of repo sync was successful. Skipping to applying source patches...\n${clear}"
-    exit 0
-  fi
+  case "$dosync" in
+    "yes"|"y")
+      # let the output of 'repo sync' tell us what to delete
+      printf "${cyanbold}>> ${cyan}First run of 'repo sync' to determine directories that need to be recloned\n${clear}"
+      if repo sync -j"$(nproc --all)" --no-tags --no-clone-bundle --current-branch --force-sync &> "$DIRS" ; then
+        printf "${magenta}The first run of repo sync was successful. Skipping to applying source patches...\n${clear}"
+      fi
   
-  # remove the cruft and keep only the list of dirs that need to be removed
-  sed -i '1,/Failing repos/d' "$DIRS"
-  sed -i '$d' "$DIRS"
+      # remove the cruft and keep only the list of dirs that need to be removed
+      sed -i '1,/Failing repos/d' "$DIRS"
+      sed -i '$d' "$DIRS"
+      ;;
+
+    "no"|"n")
+      printf "${bluebold}>> ${blue}Sync skipped.\n${clear}"
+      declare doremove="no"
+      ;;
+  esac
 
   rmdirs "$@"
   return
@@ -102,31 +120,46 @@ rmdirs() {
   local -a _dirs
   readarray -t _dirs < "${DIRS}"
 
-  # test if each dir exists, then "rm -rf" every item in dirs array
-  for _dir in "${_dirs[@]}"; do
-    printf "${greenbold}>> ${green}Removing directory '${_dir}'${clear}\n"
-    if [[ -d "${_dir}" ]]; then
-      if rm -rf "${_dir}"; then
-        printf "${cyanbold}>> ${cyan}Removed directory '${_dir}'${clear}\n"
-      else
-        fatal "Failed to remove directory '${_dir}'"
-      fi
-    else
-      fatal "Directory '${_dir}' does not exist!"
-    fi
-  done
+  case "$doremove" in
+    "yes"|"y")
+      # test if each dir exists, then "rm -rf" every item in dirs array
+      for _dir in "${_dirs[@]}"; do
+        printf "${greenbold}>> ${green}Removing directory '${_dir}'${clear}\n"
+        if [[ -d "${_dir}" ]]; then
+          if rm -rf "${_dir}"; then
+            printf "${cyanbold}>> ${cyan}Removed directory '${_dir}'${clear}\n"
+          else
+            fatal "Failed to remove directory '${_dir}'"
+          fi
+        else
+          fatal "Directory '${_dir}' does not exist!"
+        fi
+      done
+      ;;
+
+    "no"|"n")
+      printf "${bluebold}>> ${blue}Not removing conflicting directories\n${clear}"
+      ;;
+  esac
 
   sync "$@"
   return
 }
 
 sync() {
-  # run the "real" sync command
-  printf "${bluebold}>> ${blue}Syncing sources\n${clear}"
-  if ! repo sync -j$(nproc --all) --no-tags --no-clone-bundle --current-branch --force-sync ; then
-    fatal 'Failed to sync'
-  fi
+  case "$dosync" in
+    "yes"|"y")
+      # run the "real" sync command
+      printf "${bluebold}>> ${blue}Syncing sources\n${clear}"
+      if ! repo sync -j$(nproc --all) --no-tags --no-clone-bundle --current-branch --force-sync ; then
+        fatal 'Failed to sync'
+      fi
+      ;;
 
+    "no"|"n")
+      true
+      ;;
+  esac
   post "$@"
   return
 }
